# Generated by Django 4.2 on 2023-04-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='NoneTitle', max_length=128),
        ),
    ]
